import type { CSSProperties } from 'react';

import {
    AddressBook,
    AppWindow,
    Archive,
    ArrowClockwise,
    ArrowCounterClockwise,
    ArrowDown,
    ArrowDownLeft,
    ArrowLeft,
    ArrowRight,
    ArrowSquareOut,
    ArrowUDownLeft,
    ArrowUUpLeft,
    ArrowUp,
    ArrowUpRight,
    ArrowsClockwise,
    ArrowsCounterClockwise,
    ArrowsLeftRight,
    ArrowsOut,
    ArrowsOutSimple,
    Bank,
    Barbell,
    Barcode,
    Bell,
    Bookmark,
    BracketsCurly,
    Briefcase,
    Browser,
    Building,
    BuildingApartment,
    BuildingOffice,
    Buildings,
    Cake,
    Calendar,
    CalendarBlank,
    CalendarCheck,
    CalendarX,
    CaretDoubleLeft,
    CaretDoubleRight,
    CaretDown,
    CaretLeft,
    CaretRight,
    CaretUp,
    CaretUpDown,
    CashRegister,
    ChartBar,
    ChartLine,
    ChartLineUp,
    ChatCircleDots,
    ChatCircleText,
    ChatText,
    ChatsCircle,
    Check,
    CheckCircle,
    Church,
    Circle,
    CircleHalf,
    CircleNotch,
    Clock,
    ClockCountdown,
    ClockCounterClockwise,
    ClockUser,
    Cloud,
    CloudArrowDown,
    CloudArrowUp,
    CloudFog,
    CloudLightning,
    CloudRain,
    CloudSnow,
    CloudSun,
    Columns,
    Compass,
    Copy,
    CreditCard,
    CurrencyCircleDollar,
    CurrencyDollar,
    CursorClick,
    DotsThree,
    DotsThreeVertical,
    Download,
    DownloadSimple,
    Envelope,
    EnvelopeOpen,
    EnvelopeSimple,
    Equals,
    ExclamationMark,
    Eye,
    EyeSlash,
    Factory,
    File,
    FileArrowUp,
    FileCsv,
    FileDashed,
    FileDoc,
    FileImage,
    FileMagnifyingGlass,
    FilePdf,
    FileText,
    FileXls,
    Fingerprint,
    Flag,
    FlowArrow,
    Folder,
    FolderPlus,
    Funnel,
    Gauge,
    Gear,
    GearSix,
    Gift,
    Globe,
    GraduationCap,
    HandWaving,
    Handshake,
    HardDrive,
    Hash,
    Headphones,
    Hospital,
    Hourglass,
    House,
    IdentificationBadge,
    Image,
    Images,
    Info,
    Key,
    Lifebuoy,
    Lightning,
    Link,
    List,
    ListBullets,
    ListMagnifyingGlass,
    Lock,
    LockKey,
    MagicWand,
    MagnifyingGlass,
    MapPin,
    MapPinLine,
    MapTrifold,
    Medal,
    Megaphone,
    Minus,
    Moon,
    NotePencil,
    Notebook,
    Package,
    PaintBrush,
    PaperPlaneRight,
    PaperPlaneTilt,
    Paperclip,
    Password,
    Pause,
    PauseCircle,
    Pencil,
    PencilSimple,
    Percent,
    Phone,
    PhoneDisconnect,
    Play,
    PlayCircle,
    Plug,
    PlugsConnected,
    Plus,
    PlusCircle,
    Power,
    Printer,
    Prohibit,
    PushPin,
    Question,
    Receipt,
    ReceiptX,
    Rocket,
    Scales,
    SealCheck,
    ShareNetwork,
    ShieldCheck,
    ShoppingBag,
    ShoppingBagOpen,
    ShoppingCart,
    Sidebar,
    SignIn,
    SignOut,
    Sparkle,
    SpinnerGap,
    SquaresFour,
    Stack,
    Star,
    Storefront,
    Sun,
    Tag,
    Target,
    TextAa,
    TextAlignLeft,
    ThumbsUp,
    Ticket,
    Timer,
    Translate,
    Trash,
    TreeStructure,
    TrendDown,
    TrendUp,
    Truck,
    UploadSimple,
    User,
    UserCheck,
    UserCircle,
    UserCircleCheck,
    UserFocus,
    UserGear,
    UserMinus,
    UserPlus,
    Users,
    UsersThree,
    Wallet,
    Warehouse,
    Warning,
    WarningCircle,
    WarningDiamond,
    Wrench,
    X,
    XCircle,
    type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

/**
 * Icons, by name, from a fixed registry.
 *
 * ── Why a map and not a dynamic import ───────────────────────────────────────
 *
 * The server sends icon names as strings, because the module catalogue is PHP.
 * The tempting way to render them is a dynamic import keyed on the name — and
 * it is a trap twice over: the bundler cannot tree-shake an import it cannot
 * see, so the whole icon set (some nine thousand components) ends up reachable,
 * and each icon becomes its own network request, so a sidebar with fourteen
 * entries fires fourteen waterfalled fetches before it can finish drawing.
 *
 * Naming them explicitly means the bundler includes exactly these sixty, inline,
 * with no requests at all. The cost is that adding a module means adding a line
 * here — which is a compile error if forgotten, not a blank square at runtime.
 */

const REGISTRY = {
    /*
     * ── Added after an audit, not one at a time ─────────────────────────────
     *
     * An unregistered name does not fail: the lookup falls through to Circle,
     * so a missing icon is a small grey dot that looks deliberate. Nineteen of
     * them had built up across the application that way -- an Edit action whose
     * mark was a circle, a file list where every type had the same one.
     *
     * They are all names the package already ships. Nothing here was a design
     * decision; they were simply never wired up.
     */
    'app-window': AppWindow,
    'arrows-out': ArrowsOut,
    'chat-circle-text': ChatCircleText,
    'equals': Equals,
    'exclamation-mark': ExclamationMark,
    'file-csv': FileCsv,
    'file-doc': FileDoc,
    'file-image': FileImage,
    'file-pdf': FilePdf,
    'file-text': FileText,
    'file-xls': FileXls,
    'hand-waving': HandWaving,
    'hash': Hash,
    'lifebuoy': Lifebuoy,
    'note-pencil': NotePencil,
    'shopping-bag': ShoppingBag,
    'star-fill': Star,
    'text-aa': TextAa,
    'user-circle': UserCircle,
    'address-book': AddressBook,
    apartment: BuildingApartment,
    archive: Archive,
    'arrow-clockwise': ArrowClockwise,
    'arrow-counter-clockwise': ArrowCounterClockwise,
    'arrow-down': ArrowDown,
    'arrow-down-left': ArrowDownLeft,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-square-out': ArrowSquareOut,
    'arrow-u-down-left': ArrowUDownLeft,
    'arrow-u-up-left': ArrowUUpLeft,
    'arrow-up': ArrowUp,
    'arrow-up-right': ArrowUpRight,
    'arrows-clockwise': ArrowsClockwise,
    'arrows-counter-clockwise': ArrowsCounterClockwise,
    /*
     * Phosphor has no FileCheck. This screen means "a file is chosen and
     * ready to send", which FileArrowUp says — and it was rendering nothing
     * at all until now.
     */
    'file-check': FileArrowUp,
    'brackets-curly': BracketsCurly,
    'cloud-arrow-up': CloudArrowUp,
    play: Play,
    'play-circle': PlayCircle,
    'plugs-connected': PlugsConnected,
    'arrows-left-right': ArrowsLeftRight,
    'arrows-out-simple': ArrowsOutSimple,
    bank: Bank,
    barbell: Barbell,
    barcode: Barcode,
    bell: Bell,
    bookmark: Bookmark,
    briefcase: Briefcase,
    browser: Browser,
    building: Building,
    'building-office': BuildingOffice,
    buildings: Buildings,
    cake: Cake,
    calendar: Calendar,
    'calendar-blank': CalendarBlank,
    'calendar-check': CalendarCheck,
    'calendar-x': CalendarX,
    'caret-down': CaretDown,
    'caret-double-left': CaretDoubleLeft,
    'caret-double-right': CaretDoubleRight,
    'caret-left': CaretLeft,
    'caret-right': CaretRight,
    'caret-up': CaretUp,
    'caret-up-down': CaretUpDown,
    'cash-register': CashRegister,
    'chart-bar': ChartBar,
    'chart-line': ChartLine,
    'chart-line-up': ChartLineUp,
    'chat-circle-dots': ChatCircleDots,
    'chat-text': ChatText,
    'chats-circle': ChatsCircle,
    check: Check,
    'check-circle': CheckCircle,
    church: Church,
    circle: Circle,
    'circle-half': CircleHalf,
    'circle-notch': CircleNotch,
    clock: Clock,
    'clock-countdown': ClockCountdown,
    'clock-counter-clockwise': ClockCounterClockwise,
    'clock-user': ClockUser,
    cloud: Cloud,
    'cloud-arrow-down': CloudArrowDown,
    'cloud-fog': CloudFog,
    'cloud-lightning': CloudLightning,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    'cloud-sun': CloudSun,
    columns: Columns,
    compass: Compass,
    copy: Copy,
    'credit-card': CreditCard,
    'currency-circle-dollar': CurrencyCircleDollar,
    'currency-dollar': CurrencyDollar,
    'cursor-click': CursorClick,
    dot: Circle,
    'dots-three': DotsThree,
    'dots-three-vertical': DotsThreeVertical,
    download: Download,
    'download-simple': DownloadSimple,
    envelope: Envelope,
    'envelope-open': EnvelopeOpen,
    'envelope-simple': EnvelopeSimple,
    export: Download,
    eye: Eye,
    'eye-slash': EyeSlash,
    factory: Factory,
    file: File,
    'file-dashed': FileDashed,
    'file-magnifying-glass': FileMagnifyingGlass,
    fingerprint: Fingerprint,
    flag: Flag,
    'flow-arrow': FlowArrow,
    folder: Folder,
    'folder-plus': FolderPlus,
    gauge: Gauge,
    funnel: Funnel,
    gear: Gear,
    'gear-six': GearSix,
    gift: Gift,
    globe: Globe,
    'graduation-cap': GraduationCap,
    'hard-drive': HardDrive,
    handshake: Handshake,
    headphones: Headphones,
    hospital: Hospital,
    house: House,
    hourglass: Hourglass,
    'identification-badge': IdentificationBadge,
    image: Image,
    images: Images,
    info: Info,
    key: Key,
    lightning: Lightning,
    link: Link,
    list: List,
    'list-bullets': ListBullets,
    'list-magnifying-glass': ListMagnifyingGlass,
    lock: Lock,
    'lock-key': LockKey,
    'magnifying-glass': MagnifyingGlass,
    'magic-wand': MagicWand,
    'map-pin': MapPin,
    'map-pin-line': MapPinLine,
    'map-trifold': MapTrifold,
    medal: Medal,
    megaphone: Megaphone,
    minus: Minus,
    moon: Moon,
    notebook: Notebook,
    package: Package,
    'packages': Package,
    'paint-brush': PaintBrush,
    'paper-plane-right': PaperPlaneRight,
    'paper-plane-tilt': PaperPlaneTilt,
    paperclip: Paperclip,
    password: Password,
    pause: Pause,
    'pause-circle': PauseCircle,
    pencil: Pencil,
    'pencil-simple': PencilSimple,
    percent: Percent,
    phone: Phone,
    'phone-disconnect': PhoneDisconnect,
    plug: Plug,
    plus: Plus,
    'plus-circle': PlusCircle,
    power: Power,
    printer: Printer,
    prohibit: Prohibit,
    'push-pin': PushPin,
    question: Question,
    receipt: Receipt,
    'receipt-x': ReceiptX,
    rocket: Rocket,
    scales: Scales,
    'seal-check': SealCheck,
    'share-network': ShareNetwork,
    'shield-check': ShieldCheck,
    'shopping-bag-open': ShoppingBagOpen,
    'shopping-cart': ShoppingCart,
    sidebar: Sidebar,
    'sign-in': SignIn,
    'sign-out': SignOut,
    sparkle: Sparkle,
    spinner: SpinnerGap,
    'spinner-gap': SpinnerGap,
    'squares-four': SquaresFour,
    stack: Stack,
    star: Star,
    storefront: Storefront,
    sun: Sun,
    swap: ArrowsLeftRight,
    tag: Tag,
    target: Target,
    'text-align-left': TextAlignLeft,
    'thumbs-up': ThumbsUp,
    ticket: Ticket,
    timer: Timer,
    translate: Translate,
    trash: Trash,
    'tree-structure': TreeStructure,
    'trend-down': TrendDown,
    'trend-up': TrendUp,
    truck: Truck,
    upload: UploadSimple,
    'upload-simple': UploadSimple,
    user: User,
    'user-check': UserCheck,
    'user-circle-check': UserCircleCheck,
    'user-focus': UserFocus,
    'user-gear': UserGear,
    'user-minus': UserMinus,
    'user-plus': UserPlus,
    users: Users,
    'users-three': UsersThree,
    'wallet': Wallet,
    warehouse: Warehouse,
    warning: Warning,
    'warning-circle': WarningCircle,
    'warning-diamond': WarningDiamond,
    wrench: Wrench,
    x: X,
    'x-circle': XCircle,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof REGISTRY;

type IconProps = {
    name: string;
    size?: number;
    weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
    className?: string;
    style?: CSSProperties;
};

export function Icon({ name, size = 18, weight = 'bold', className, style }: IconProps) {
    // A name the server sent that this build does not know about — which
    // happens for exactly one deploy, between the PHP shipping and the TSX
    // shipping. A neutral dot beats a crash or an empty gap.
    const Component = REGISTRY[name as IconName] ?? Circle;

    // Caret/chevron icons look better in regular weight, not duotone.
    // Everything else gets the requested weight (bold is default).
    const iconWeight = name && name.startsWith('caret-') ? 'regular' : weight;

    return <Component size={size} weight={iconWeight} className={className} style={style} aria-hidden />;
}
