import type { CSSProperties } from 'react';

import {
    AddressBook,
    ArrowCounterClockwise,
    ArrowLeft,
    ArrowRight,
    ArrowsClockwise,
    ArrowsLeftRight,
    ArrowSquareOut,
    ArrowsOutSimple,
    ArrowUp,
    ArrowUDownLeft,
    ArrowUpRight,
    Bank,
    Bell,
    Briefcase,
    Building,
    BuildingApartment,
    BuildingOffice,
    Buildings,
    CalendarCheck,
    CaretDown,
    CaretLeft,
    CaretRight,
    CaretUp,
    CaretUpDown,
    CashRegister,
    ChartLine,
    ChartLineUp,
    ChatsCircle,
    ChatText,
    Check,
    CheckCircle,
    Church,
    Circle,
    ClockUser,
    Cloud,
    CloudArrowDown,
    CloudFog,
    CloudLightning,
    CloudRain,
    CloudSnow,
    CloudSun,
    Columns,
    Compass,
    Copy,
    CurrencyCircleDollar,
    DotsThree,
    DotsThreeVertical,
    Envelope,
    Eye,
    EyeSlash,
    Factory,
    FileMagnifyingGlass,
    Fingerprint,
    FlowArrow,
    Gear,
    GearSix,
    Gift,
    GraduationCap,
    Handshake,
    Hospital,
    House,
    Image,
    Images,
    Info,
    Key,
    List,
    ListMagnifyingGlass,
    MagnifyingGlass,
    Medal,
    Megaphone,
    Moon,
    Notebook,
    PaperPlaneRight,
    Package,
    PaintBrush,
    PauseCircle,
    PencilSimple,
    Plus,
    PlusCircle,
    Plug,
    PushPin,
    Receipt,
    ReceiptX,
    Scales,
    SealCheck,
    ShieldCheck,
    ShoppingBagOpen,
    ShoppingCart,
    Sidebar,
    SignOut,
    Sparkle,
    SpinnerGap,
    SquaresFour,
    Star,
    Storefront,
    Sun,
    Tag,
    Target,
    Trash,
    TreeStructure,
    TrendDown,
    TrendUp,
    Truck,
    UploadSimple,
    User,
    UserFocus,
    UserPlus,
    UsersThree,
    Wallet,
    Warehouse,
    Warning,
    WarningCircle,
    WarningDiamond,
    Wrench,
    X,
    type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

/**
 * Icons, by name, from a fixed registry.
 *
 * ── Why a map and not a dynamic import ───────────────────────────────────────
 *
 * The server sends icon names as strings, because the module catalogue is PHP.
 * The tempting way to render them is a dynamic import keyed on the name — and
 * it is a trap twice over: the bundler cannot tree-shake an import it cannot
 * see, so the whole icon set (some nine thousand components) ends up reachable,
 * and each icon becomes its own network request, so a sidebar with fourteen
 * entries fires fourteen waterfalled fetches before it can finish drawing.
 *
 * Naming them explicitly means the bundler includes exactly these sixty, inline,
 * with no requests at all. The cost is that adding a module means adding a line
 * here — which is a compile error if forgotten, not a blank square at runtime.
 */

const REGISTRY = {
    'address-book': AddressBook,
    'arrow-counter-clockwise': ArrowCounterClockwise,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-square-out': ArrowSquareOut,
    'arrow-u-down-left': ArrowUDownLeft,
    'arrow-up': ArrowUp,
    'arrow-up-right': ArrowUpRight,
    'arrows-clockwise': ArrowsClockwise,
    'arrows-left-right': ArrowsLeftRight,
    'arrows-out-simple': ArrowsOutSimple,
    apartment: BuildingApartment,
    bank: Bank,
    bell: Bell,
    briefcase: Briefcase,
    building: Building,
    'building-office': BuildingOffice,
    buildings: Buildings,
    'calendar-check': CalendarCheck,
    'caret-down': CaretDown,
    'caret-left': CaretLeft,
    'caret-right': CaretRight,
    'caret-up': CaretUp,
    'caret-up-down': CaretUpDown,
    'cash-register': CashRegister,
    'chart-line': ChartLine,
    'chart-line-up': ChartLineUp,
    'chat-text': ChatText,
    'chats-circle': ChatsCircle,
    check: Check,
    'check-circle': CheckCircle,
    church: Church,
    'clock-user': ClockUser,
    cloud: Cloud,
    'cloud-arrow-down': CloudArrowDown,
    'cloud-fog': CloudFog,
    'cloud-lightning': CloudLightning,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    'cloud-sun': CloudSun,
    columns: Columns,
    compass: Compass,
    copy: Copy,
    'currency-circle-dollar': CurrencyCircleDollar,
    dot: Circle,
    'dots-three': DotsThree,
    'dots-three-vertical': DotsThreeVertical,
    envelope: Envelope,
    eye: Eye,
    'eye-slash': EyeSlash,
    factory: Factory,
    'file-magnifying-glass': FileMagnifyingGlass,
    fingerprint: Fingerprint,
    'flow-arrow': FlowArrow,
    gear: Gear,
    'gear-six': GearSix,
    gift: Gift,
    'graduation-cap': GraduationCap,
    handshake: Handshake,
    hospital: Hospital,
    house: House,
    image: Image,
    images: Images,
    info: Info,
    key: Key,
    list: List,
    'list-magnifying-glass': ListMagnifyingGlass,
    'magnifying-glass': MagnifyingGlass,
    medal: Medal,
    megaphone: Megaphone,
    moon: Moon,
    notebook: Notebook,
    package: Package,
    'paint-brush': PaintBrush,
    'paper-plane-right': PaperPlaneRight,
    'pause-circle': PauseCircle,
    'pencil-simple': PencilSimple,
    plug: Plug,
    plus: Plus,
    'plus-circle': PlusCircle,
    'push-pin': PushPin,
    receipt: Receipt,
    'receipt-x': ReceiptX,
    scales: Scales,
    'seal-check': SealCheck,
    'shield-check': ShieldCheck,
    'shopping-bag-open': ShoppingBagOpen,
    'shopping-cart': ShoppingCart,
    sidebar: Sidebar,
    'sign-out': SignOut,
    sparkle: Sparkle,
    spinner: SpinnerGap,
    'spinner-gap': SpinnerGap,
    'squares-four': SquaresFour,
    star: Star,
    storefront: Storefront,
    sun: Sun,
    swap: ArrowsLeftRight,
    tag: Tag,
    target: Target,
    trash: Trash,
    'tree-structure': TreeStructure,
    'trend-down': TrendDown,
    'trend-up': TrendUp,
    truck: Truck,
    upload: UploadSimple,
    'upload-simple': UploadSimple,
    user: User,
    'user-focus': UserFocus,
    'user-plus': UserPlus,
    'users-three': UsersThree,
    wallet: Wallet,
    warehouse: Warehouse,
    warning: Warning,
    'warning-circle': WarningCircle,
    'warning-diamond': WarningDiamond,
    wrench: Wrench,
    x: X,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof REGISTRY;

type IconProps = {
    name: string;
    size?: number;
    weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
    className?: string;
    style?: CSSProperties;
};

export function Icon({ name, size = 18, weight = 'bold', className, style }: IconProps) {
    // A name the server sent that this build does not know about — which
    // happens for exactly one deploy, between the PHP shipping and the TSX
    // shipping. A neutral dot beats a crash or an empty gap.
    const Component = REGISTRY[name as IconName] ?? Circle;

    return <Component size={size} weight={weight} className={className} style={style} aria-hidden />;
}
