{{--
    The PDF's own stylesheet.

    Written as literal colours rather than our CSS custom properties, and this is
    the one place that is correct: dompdf resolves no variables, and there is no
    theme to follow — a printed page is a printed page. The values are the light
    theme's tokens, copied deliberately, so the export still looks like the
    product it came from.
--}}
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
    @page { margin: 26mm 18mm; }

    body {
        font-family: 'DejaVu Sans', sans-serif;
        font-size: 10pt;
        color: #2e3d52;
        margin: 0;
    }

    .head {
        border-bottom: 2px solid #0891b2;
        padding-bottom: 10px;
        margin-bottom: 18px;
    }

    .title { font-size: 17pt; font-weight: bold; color: #0d1b2a; margin: 0; }
    .sub { font-size: 9pt; color: #7a8fa6; margin: 4px 0 0; }

    .chips { margin: 8px 0 0; }
    .chip {
        display: inline-block;
        background: #ecfeff;
        color: #0e7490;
        border-radius: 3px;
        padding: 2px 7px;
        font-size: 8pt;
        font-weight: bold;
        margin-right: 4px;
    }

    table { width: 100%; border-collapse: collapse; margin-top: 6px; }

    th {
        background: #0891b2;
        color: #fff;
        text-align: left;
        font-size: 8.5pt;
        padding: 7px 9px;
    }

    td {
        padding: 7px 9px;
        border-bottom: 1px solid #d6eaf8;
        font-size: 9.5pt;
    }

    td.num { text-align: right; font-weight: bold; color: #0d1b2a; }

    .up { color: #2e7d32; font-weight: bold; }
    .down { color: #b71c1c; font-weight: bold; }
    .flat { color: #7a8fa6; }

    .meta { width: 100%; margin-bottom: 16px; font-size: 9pt; }
    .meta td { border: 0; padding: 2px 0; }
    .meta .k { color: #7a8fa6; width: 90px; }

    .foot {
        margin-top: 22px;
        border-top: 1px solid #d6eaf8;
        padding-top: 8px;
        font-size: 7.5pt;
        color: #a8bed4;
    }
</style>
</head>
<body>

<div class="head">
    <p class="title">{{ $meta['business'] }}</p>
    <p class="sub">Overview · {{ $meta['from'] }} to {{ $meta['to'] }}</p>

    @if ($meta['categories'] !== '')
        <p class="chips">
            @foreach (explode(', ', $meta['categories']) as $category)
                <span class="chip">{{ $category }}</span>
            @endforeach
        </p>
    @endif
</div>

<table class="meta">
    <tr><td class="k">Currency</td><td>{{ $meta['currency'] }}</td></tr>
    <tr><td class="k">Generated</td><td>{{ $meta['generated'] }}</td></tr>
</table>

<table>
    <thead>
        <tr>
            <th>Measure</th>
            <th style="text-align:right">Value</th>
            <th style="text-align:right">Change</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($rows as $row)
            <tr>
                <td>{{ $row[0] }}</td>
                <td class="num">{{ $row[1] }}</td>
                <td class="num {{ strtolower($row[3]) }}">{{ $row[2] }}</td>
            </tr>
        @empty
            {{-- An empty report is a real answer: books with nothing posted yet.
                 Saying so beats a page of confident zeroes. --}}
            <tr><td colspan="3" style="text-align:center;color:#7a8fa6;padding:18px">
                Nothing recorded for this period.
            </td></tr>
        @endforelse
    </tbody>
</table>

<p class="foot">
    Generated by Angisflow on {{ $meta['generated'] }}. Figures cover
    {{ $meta['from'] }} to {{ $meta['to'] }} for {{ $meta['business'] }}.
</p>

</body>
</html>
