<?php

declare(strict_types=1);

namespace App\Domain\Vault;

use App\Domain\Tenancy\TenantContext;
use App\Domain\Vault\Models\Credential;
use Illuminate\Support\Collection;
use RuntimeException;

/**
 * The credential vault.
 *
 * The only class in the codebase that stores or retrieves credential payloads.
 * Everything else holds a ref string and calls retrieve() when it needs the
 * actual secret — which means the secret is decrypted exactly once, used, and
 * discarded, rather than sitting in a model attribute for the lifetime of the
 * request.
 *
 * ── What "rotation" means here ───────────────────────────────────────────────
 *
 * Rotation replaces the payload in place and stamps last_rotated_at. The ref
 * does not change, so every table that points at this credential continues to
 * work without any update. The old payload is gone — there is no rotation
 * history in this version. If a full audit trail is needed later, a
 * credential_rotations table can be added without changing this one.
 *
 * ── What "revoke" means ───────────────────────────────────────────────────────
 *
 * Revoke sets is_active = false and clears the payload. The ref remains so
 * that tables pointing at it can detect the revocation (retrieve() throws on
 * an inactive credential) rather than silently getting null.
 */
class Vault
{
    public function __construct(
        private readonly TenantContext $tenant,
    ) {}

    /**
     * Store a new credential and return its ref.
     *
     * The ref is what the caller stores in credential_ref columns. It is the
     * same ULID as the public_id, generated by HasPublicId on create.
     *
     * @param  array<string, mixed>  $payload
     */
    public function store(string $label, string $kind, array $payload): Credential
    {
        $this->validateKind($kind);

        // Generate the ULID here so ref and public_id are the same value and
        // both arrive in the INSERT together — no dependency on boot order.
        $ref = strtolower((string) \Illuminate\Support\Str::ulid());

        return Credential::create([
            'public_id'       => $ref,
            'ref'             => $ref,
            'account_id'      => $this->tenant->accountId(),
            'label'           => $label,
            'kind'            => $kind,
            'payload'         => $payload,
            'last_rotated_at' => now(),
        ]);
    }

    /**
     * Retrieve the decrypted payload for a ref.
     *
     * Stamps last_used_at so stale credentials can be found. Throws if the
     * ref does not exist in this account or the credential has been revoked.
     *
     * @return array<string, mixed>
     */
    public function retrieve(string $ref): array
    {
        $credential = $this->findRef($ref);

        if (! $credential->is_active) {
            throw new RuntimeException(
                "The credential \"{$credential->label}\" has been revoked and can no longer be used."
            );
        }

        $credential->timestamps = false;
        $credential->update(['last_used_at' => now()]);
        $credential->timestamps = true;

        // makeVisible() temporarily lifts the hidden guard so the cast runs.
        return $credential->makeVisible('payload')->payload;
    }

    /**
     * Replace the payload without changing the ref.
     *
     * @param  array<string, mixed>  $newPayload
     */
    public function rotate(string $ref, array $newPayload): Credential
    {
        $credential = $this->findRef($ref);

        $credential->update([
            'payload'         => $newPayload,
            'last_rotated_at' => now(),
        ]);

        return $credential->fresh();
    }

    /**
     * Disable a credential and clear its payload.
     *
     * The ref row stays so that tables pointing at it can detect the
     * revocation rather than getting a missing-ref error.
     */
    public function revoke(string $ref): void
    {
        $credential = $this->findRef($ref);

        $credential->update([
            'is_active' => false,
            'payload'   => [],
        ]);
    }

    /**
     * All credentials for the current account — payloads excluded.
     *
     * @return Collection<int, Credential>
     */
    public function list(): Collection
    {
        return Credential::query()
            ->orderBy('label')
            ->get();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function findRef(string $ref): Credential
    {
        $credential = Credential::where('ref', $ref)->first();

        if ($credential === null) {
            throw new RuntimeException(
                "No credential with ref {$ref} exists in this account."
            );
        }

        return $credential;
    }

    private function validateKind(string $kind): void
    {
        $allowed = [
            Credential::KIND_API_KEY,
            Credential::KIND_OAUTH_TOKEN,
            Credential::KIND_BASIC_AUTH,
            Credential::KIND_GENERIC,
        ];

        if (! in_array($kind, $allowed, true)) {
            throw new RuntimeException(
                "Unknown credential kind \"{$kind}\". Allowed: ".implode(', ', $allowed).'.'
            );
        }
    }
}
